[project]
name = "continue-viz"
version = "0.1.0"
description = "quick visualizations for continue dev data"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.2.3",
    "streamlit>=1.44.0",
]
